language: go

go:
- "1.12.x"

addons:
  apt:
    packages:
    - rpm

env:
- GO111MODULE=on

deploy:
- provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
